USE Dismissal
BEGIN TRANSACTION SET DEADLOCK_PRIORITY HIGH
UPDATE Employee
SET EnterDate = '2020-03-20' WHERE EmpID = 5

WAITFOR DELAY '00:00:10'

UPDATE DismissalDocument 
SET Compensation = 23000 WHERE EmpID = 8

COMMIT TRANSACTION