USE dismissal
ALTER TABLE DismissalDocument
ALTER COLUMN DocumentID INTEGER NOT NULL
ALTER TABLE DismissalDocument
ALTER COLUMN Number VARCHAR(4) NULL
ALTER TABLE DismissalDocument
ALTER COLUMN RegDate DATE NULL
ALTER TABLE DismissalDocument
ALTER COLUMN DismissalDate DATE NULL
ALTER TABLE DismissalDocument
ALTER COLUMN ArticleID INTEGER NULL
ALTER TABLE DismissalDocument
ALTER COLUMN EmpID INTEGER NULL
ALTER TABLE DismissalDocument
ALTER COLUMN Compensation DECIMAL(10, 4) NULL
ALTER TABLE DismissalDocument
ADD CONSTRAINT pk_DocumentID PRIMARY KEY (DocumentID)
ALTER TABLE DismissalDocument
ADD CONSTRAINT default_EmpID DEFAULT 0 FOR EmpID
ALTER TABLE DismissalDocument
ADD CONSTRAINT default_ArticleID DEFAULT 0 FOR ArticleID
ALTER TABLE DismissalDocument
ADD CONSTRAINT fk_article FOREIGN KEY (ArticleID)
REFERENCES DismissalArticle (ArticleID) ON UPDATE SET DEFAULT ON DELETE SET DEFAULT
ALTER TABLE DismissalDocument
ADD CONSTRAINT fk_employee FOREIGN KEY (EmpID)
REFERENCES Employee (EmpID) ON UPDATE SET DEFAULT ON DELETE SET DEFAULT