USE Dismissal
ALTER TABLE DismissalArticle
ALTER COLUMN ArticleID INTEGER NOT NULL
ALTER TABLE DismissalArticle
ALTER COLUMN Name NVARCHAR(50) NULL
ALTER TABLE DismissalArticle
ALTER COLUMN Reason TEXT NULL
ALTER TABLE DismissalArticle
ALTER COLUMN Number INTEGER NULL
ALTER TABLE DismissalArticle
ALTER COLUMN ParagraphNumber NVARCHAR(4) NULL
ALTER TABLE DismissalArticle
ADD CONSTRAINT pk_ArticleID PRIMARY KEY (ArticleID)