USE Dismissal
ALTER TABLE Employee 
ALTER COLUMN EmpID INTEGER NOT NULL
ALTER TABLE Employee
ALTER COLUMN LastName NVARCHAR(30) NULL
ALTER TABLE Employee
ALTER COLUMN FirstName NVARCHAR(25) NULL
ALTER TABLE Employee
ALTER COLUMN MiddleName NVARCHAR(25) NULL
ALTER TABLE Employee 
ALTER COLUMN JobTitle NVARCHAR(40) NULL
ALTER TABLE Employee 
ALTER COLUMN DepartmentName NVARCHAR(30) NULL
ALTER TABLE Employee
ALTER COLUMN EnterDate DATE NULL
ALTER TABLE Employee
ADD CONSTRAINT PK_unique PRIMARY KEY (EmpID)